name: CI 

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        haxe:
          - 3.4.7
          - 4.3.6
        target:
          - neko
          - python
          - php
          - cpp
          - node
          - java -D jvm
          - cs
        
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lix
        run: npm add -g lix

      - name: Install Haxe
        run: lix install haxe ${{ matrix.haxe }}

      - name: Install Haxe Libraries
        run: lix download

      - name: Run tests
        run: lix run travix ${{ matrix.target }}
