name: Run tests on master 

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        haxe:
        - 3.4.7
        - 4.3.6
        
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Test with Haxe
      uses: vegardit/haxe-reusable-workflows/.github/actions/test-with-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}
        haxe-libs: hx3compat
        output-dir: bin
        
        test-cpp:    true
        test-cs:     true
        # test-eval:   true
        test-hl:      ${{ matrix.haxe != '3.4.7' }}
        test-java:   true
        # test-jvm:    true
        # test-lua:    true
        test-neko:   true
        test-node:   true
        test-php:    true
        test-python: true

